- name: Add GitLab EE repository
  apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/ $(lsb_release -cs) main"
    state: present

- name: Add GitLab EE GPG Key
  shell: |
    curl -fsSL https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey | sudo apt-key add -

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install GitLab EE
  apt:
    name: gitlab-ee
    state: present

- name: Set GitLab external URL
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: 'external_url "http://192.168.64.4"'

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure
